#!/usr/bin/env bash

if [ $# == 1 ]; then

    if [ "$1" == "start" ]; then

        echo "Start Galaxy Tool Generator (GTG) ..."

        mkdir -p GTG_workspace

        elif [ "$1" == "stop" ]; then

        echo "Stop Galaxy Tool Generator (GTG) ..."

    fi

else

    echo "Please specify a command"

fi



