#!/usr/bin/env bash

while getopts ":mp" opt; do
  case $opt in
    m)
      echo "-m was triggered! $1 was entered" >&2
      ;;
    p)
      echo "-m was triggered! $1 was entered" >&2
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done


if [ $# -gt 0 ]; then

    if [ "$1" == "start" ]; then

        echo "Start Galaxy Tool Generator (GTG) ..."

        mkdir -p GTG_workspace

        elif [ "$1" == "stop" ]; then

        echo "Stop Galaxy Tool Generator (GTG) ..."

    fi

else

    echo "Please specify a command"

fi



